sudo: required
services:
  - docker

script:
  - docker build -t saifullahkatpar/travis .
  - docker images saifullahkatpar/travis

before_deploy:
  - docker login -u saifullahkatpar  -p Guru99@123

deploy:
  provider: script
  script: docker push saifullahkatpar/travis
  on:
    branch: master
