sudo: required
services:
  - docker

script:
  - docker build -t saifullah/travis .
  - docker images saifullah/travis

before_deploy:
  - docker login -u saifullah  -p Guru99@123

deploy:
  provider: script
  script: docker push saifullah/travis
  on:
    branch: master
